In [1]:
import tensorflow as tf
import random
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import time
import csv

In [2]:
hidden_dim = 20
location_num = 4
training_step = 100

##tr
filename0_tr = "wifi_ET_0_1472570446"
filename1_tr = "wifi_ET_1_1472593839"
filename2_tr = "wifi_ET_2_1472598476"
filename3_tr = "wifi_ET_3_1472590170"

##te
filename0_te = "wifi_ET_0_1472546966"
filename1_te = "wifi_ET_1_1472554884"
filename2_te = "wifi_ET_2_1472551231"
filename3_te = "wifi_ET_3_1472564959"

In [3]:
def to_ndarray(list):
    lgt = len(list)
    x = np.zeros((1,lgt),dtype ='float')
    for i in range(0,lgt):
        x[0,i]=list[i]
    return x

def to_y_binary_array(list, location_num):
    lgt = len(list)
    out_list = np.zeros((lgt, location_num))
    for i in range(0,lgt):
        if list[i] == '0':
            out_list[i,0] = 1
        elif list[i] == '1' :
            out_list[i,1]=1
        elif list[i] == '2' :
            out_list[i,2] = 1
        else :
            out_list[i,3] = 1
    return out_list

def weight_variable(shape):
    initial = tf.truncated_normal(shape, stddev=0.1)
    return tf.Variable(initial)

def bias_variable(shape):
    initial = tf.constant(0.1, shape=shape)
    return tf.Variable(initial)

In [4]:
def read_wifi_data(filename,signal,location,address_index):
    filename = "data/wifi_et/"+filename+".csv"
    with open (filename,'rb') as csvfile:
        reader = csv.reader(csvfile, delimiter = ',')
        for row in reader:
            signal.append(row[3])
            location.append(row[4])
            if row[2] not in address_index:
                address_index.append(row[2])

In [5]:
signal_tr = []
location_tr = []
address_index_tr = []

signal_te = []
location_te = []
address_index_te = []

read_wifi_data(filename0_tr,signal_tr,location_tr, address_index_tr)
read_wifi_data(filename1_tr,signal_tr,location_tr, address_index_tr)
read_wifi_data(filename2_tr,signal_tr,location_tr, address_index_tr)
read_wifi_data(filename3_tr,signal_tr,location_tr, address_index_tr)

read_wifi_data(filename0_te,signal_te,location_te, address_index_te)
read_wifi_data(filename1_te,signal_te,location_te, address_index_te)
read_wifi_data(filename2_te,signal_te,location_te, address_index_te)
read_wifi_data(filename3_te,signal_te,location_te, address_index_te)

tr_data_num = len(signal_tr)
te_data_num = len(signal_te)

In [6]:
tr_x = to_ndarray(signal_tr)
tr_y = to_y_binary_array(location_tr,location_num)

te_x = to_ndarray(signal_te)
te_y = to_y_binary_array(location_te,location_num)

print tr_x, tr_y, te_x , te_y

[[-56. -53. -72. ..., -88. -89. -89.]] [[ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 ..., 
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]] [[-48. -59. -59. ..., -89. -92. -96.]] [[ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 ..., 
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]]


In [7]:
W = weight_variable([1,hidden_dim])
b = bias_variable([hidden_dim])

W2 = weight_variable([hidden_dim,location_num])
b2 = bias_variable([location_num])

X = tf.placeholder("float",[None,1])
Y = tf.placeholder("float",[None,location_num])

hidden = tf.nn.relu(tf.matmul(X,W)+b)
sfmax = tf.nn.softmax(tf.matmul(hidden,W2)+b2)

cross_entropy = -tf.reduce_sum(Y*tf.log(sfmax))
train = tf.train.AdamOptimizer(1e-2).minimize(cross_entropy)

In [8]:
print tr_data_num,te_data_num

9041 8479


In [10]:
init = tf.initialize_all_variables()

sess = tf.Session()
sess.run(init)

start_time = time.time()
for step in xrange(training_step):
    tr_x = np.reshape(tr_x,(-1,1))
    te_x = np.reshape(te_x,(-1,1))
    sess.run(train, feed_dict = {X: tr_x, Y: tr_y})
    correct_prediction = tf.equal(tf.argmax(sfmax,1), tf.argmax(Y,1))
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))
    print sess.run(accuracy,feed_dict = {X: te_x, Y: te_y})
        
excute_time = time.time() - start_time

0.382238
0.207454
0.207454
0.207454
0.207454
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.207454
0.207454
0.207454
0.207454
0.265951
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238
0.382238


In [ ]:
print tr_x, tr_y

# 결과

In [ ]:
test_0x_label = []
test_0y_label = []
read_wifi_data(filename0_te,test_0x_label,test_0y_label, address_index_te)
bc_x = np.reshape(test_0x_label,(-1,1))
gain_0y_label = sfmax.eval({X: bc_x},sess)
print gain_0y_label

In [ ]:
test_1x_label = []
test_1y_label = []
read_wifi_data(filename1_te,test_1x_label,test_1y_label, address_index_te)
bc_x = np.reshape(test_1x_label,(-1,1))
gain_1y_label = sfmax.eval({X: bc_x},sess)
print gain_1y_label

In [ ]:
test_2x_label = []
test_2y_label = []
read_wifi_data(filename2_te,test_2x_label,test_2y_label, address_index_te)
bc_x = np.reshape(test_2x_label,(-1,1))
gain_2y_label = sfmax.eval({X: bc_x},sess)
print gain_2y_label

In [ ]:
test_3x_label = []
test_3y_label = []
read_wifi_data(filename3_te,test_3x_label,test_3y_label, address_index_te)
bc_x = np.reshape(test_3x_label,(-1,1))
gain_1y_label = sfmax.eval({X: bc_x},sess)
print gain_1y_label

# 디스커션

data set의 갯수만큼의 확률을 나타냄
[3119, 2380, 1511, 2017] 개의 data와 nn을 통과한 data가 유사한 확률을 보임.

# 이유

1. 각 x_data 즉, ap signal 신호가 서로 산재해 있어서 그 신호자체만으로는 ap address dimension을 이룰수가 없음.
         1-1. hidden dimension의 크기를 조정해봐도 아무런 효과가 없는 것으로 보아, dimension은 현재 아무런 의미가 없는 것이 확실하다.
2. 그 상황에서 label의 비중자체가 하나의 dimension으로 자리잡게 됨

# 개선방안

1. 시간마다 모은 dataset을 입력으로 받아옴 (예:00:27:1c:9 = -56, 00:23:11:cc = =74)
2. 이렇게 되면 ap address로 dimension을 분화시킬 수 있을 것이라고 생각함.

# 생각해 봐야할 점

activation function을 relu를 썼을 때를 제외하고, tanh, sigmoid를 이용하였을 때에는 weight가 satuation이 된 것처럼 모든 sfmax set이 같은 값을 갖고 있었음.