In [1]:
import tensorflow as tf
from tensorflow.python.ops import rnn, rnn_cell
import numpy as np

In [2]:
char_rdic = ['h','e','l','o'] #id-> char
char_dic = {w: i for i, w in enumerate(char_rdic)} # char->id
x_data = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,1,0]],dtype = 'f') #hell

sample = [char_dic[c] for c in "hello"] # to index

In [3]:
char_vocab_size = len(char_dic)
rnn_size = char_vocab_size # 1 hot coding(one of 4)
batch_size = 1 # one sample
time_step_size = 4 # 'hell'=>'ello'

In [4]:
#RNN model  rnn_size = output size, 와파핑프에서는 4개방
rnn_cell = rnn_cell.BasicRNNCell(rnn_size) 
state = tf.zeros([batch_size,rnn_cell.state_size])
X_split = tf.split(0,time_step_size, x_data)
outputs, state = rnn.rnn(rnn_cell,X_split,state)

In [5]:
logits = tf.reshape(tf.concat(1,outputs),[-1,rnn_size])
targets = tf.reshape(sample[1:],[-1])
weights = tf.ones([time_step_size*batch_size])

loss = tf.nn.seq2seq.sequence_loss_by_example([logits],[targets],[weights])
cost = tf.reduce_sum(loss)/batch_size
train_op = tf.train.RMSPropOptimizer(0.01,0.9).minimize(cost)

In [6]:
print(logits)
print(targets)
print(weights)

Tensor("Reshape:0", shape=(4, 4), dtype=float32)
Tensor("Reshape_1:0", shape=(4,), dtype=int32)
Tensor("ones:0", shape=(4,), dtype=float32)


In [7]:
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    for i in range(100):
        sess.run(train_op)
        result = sess.run(tf.arg_max(logits,1))
        print (result,[char_rdic[t] for t in result])

[0 2 1 1] ['h', 'l', 'e', 'e']
[0 2 1 1] ['h', 'l', 'e', 'e']
[1 2 1 1] ['e', 'l', 'e', 'e']
[1 2 1 1] ['e', 'l', 'e', 'e']
[1 2 1 1] ['e', 'l', 'e', 'e']
[1 2 1 1] ['e', 'l', 'e', 'e']
[1 2 1 1] ['e', 'l', 'e', 'e']
[1 2 1 1] ['e', 'l', 'e', 'e']
[1 2 1 1] ['e', 'l', 'e', 'e']
[1 2 1 1] ['e', 'l', 'e', 'e']
[1 2 1 1] ['e', 'l', 'e', 'e']
[1 2 1 1] ['e', 'l', 'e', 'e']
[1 2 1 1] ['e', 'l', 'e', 'e']
[1 2 1 1] ['e', 'l', 'e', 'e']
[1 2 1 1] ['e', 'l', 'e', 'e']
[1 2 1 1] ['e', 'l', 'e', 'e']
[1 2 1 1] ['e', 'l', 'e', 'e']
[1 2 1 1] ['e', 'l', 'e', 'e']
[1 2 1 1] ['e', 'l', 'e', 'e']
[1 2 1 1] ['e', 'l', 'e', 'e']
[1 2 1 1] ['e', 'l', 'e', 'e']
[1 2 1 1] ['e', 'l', 'e', 'e']
[1 2 1 1] ['e', 'l', 'e', 'e']
[1 2 1 1] ['e', 'l', 'e', 'e']
[1 2 1 1] ['e', 'l', 'e', 'e']
[1 2 1 3] ['e', 'l', 'e', 'o']
[1 2 1 3] ['e', 'l', 'e', 'o']
[1 2 1 3] ['e', 'l', 'e', 'o']
[1 2 1 3] ['e', 'l', 'e', 'o']
[1 2 1 3] ['e', 'l', 'e', 'o']
[1 2 2 3] ['e', 'l', 'l', 'o']
[1 2 2 3] ['e', 'l', 'l', 'o']
[1 2 2 3

ValueError: Cannot evaluate tensor using `eval()`: No default session is registered. Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`