텐서플로우에서 제공하는 툴을 이용해 MNIST 데이터를 다운받습니다.

In [1]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


In [2]:
import tensorflow as tf

In [3]:
tf.convert_to_tensor(mnist.train.images).get_shape()

TensorShape([Dimension(55000), Dimension(784)])

가중치 텐서와 바이어스 텐서를 만듭니다.

In [4]:
import tensorflow as tf

W = tf.Variable(tf.zeros([784,10]))
b = tf.Variable(tf.zeros([10]))

훈련 이미지 데이터를 넣을 플레이스홀더와 소프트맥스 텐서를 만듭니다.

In [5]:
x = tf.placeholder("float", [None, 784])
y = tf.nn.softmax(tf.matmul(x,W) + b)

실제 레이블을 담기위한 텐서와 교차 엔트로피 방식을 이용하는 그래디언트 디센트 방식을 선택합니다.

In [6]:
y_ = tf.placeholder("float", [None,10])
cross_entropy = -tf.reduce_sum(y_*tf.log(y))
train_step = tf.train.GradientDescentOptimizer(0.01).minimize(cross_entropy)

변수를 초기화하고 세션을 시작합니다.

In [7]:
sess = tf.Session()
sess.run(tf.initialize_all_variables())

1000의 반복을 수행하고 결과를 출력합니다. 최종 정확도는 91% 정도 입니다.

In [8]:
for i in range(1000):
    batch_xs, batch_ys = mnist.train.next_batch(100)
    sess.run(train_step, feed_dict={x: batch_xs, y_: batch_ys})
    correct_prediction = tf.equal(tf.argmax(y,1), tf.argmax(y_,1))
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))
    print(sess.run(accuracy, feed_dict={x: mnist.test.images, y_: mnist.test.labels}))

0.4075
0.3573
0.5091
0.4416
0.5773
0.519
0.613
0.6506
0.7404
0.8002
0.8245
0.7839
0.6919
0.7013
0.7577
0.7891
0.7871
0.8041
0.8135
0.7161
0.6986
0.7697
0.7746
0.7777
0.8541
0.825
0.814
0.8054
0.7779
0.8358
0.8402
0.8028
0.84
0.8404
0.8309
0.8421
0.8549
0.8157
0.7435
0.8559
0.8656
0.8628
0.8554
0.8338
0.8381
0.8484
0.8503
0.8619
0.8646
0.8435
0.8545
0.8758
0.7996
0.8518
0.8405
0.8553
0.8642
0.8737
0.8841
0.8848
0.8795
0.8732
0.8403
0.8724
0.8751
0.8606
0.8729
0.8573
0.8545
0.8261
0.8494
0.8066
0.868
0.8388
0.8787
0.826
0.8556
0.8805
0.8821
0.8888
0.8624
0.8667
0.8747
0.8852
0.8875
0.8876
0.8818
0.8885
0.8817
0.871
0.8047
0.8312
0.845
0.8578
0.8671
0.8565
0.7704
0.8124
0.8864
0.892
0.894
0.871
0.8736
0.8674
0.8832
0.8954
0.8911
0.8973
0.8932
0.8902
0.8942
0.8857
0.8955
0.8942
0.8696
0.8859
0.8957
0.8979
0.8988
0.8905
0.8961
0.8983
0.896
0.8939
0.8695
0.8817
0.8947
0.8852
0.8973
0.8899
0.8968
0.9008
0.8766
0.9009
0.8612
0.9009
0.8971
0.9028
0.9031
0.9028
0.9022
0.8989
0.8806
0.8835
0.8816

In [11]:
print batch_xs, batch_ys

[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]] [[ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0. 

In [10]:
print y.eval({x:  mnist.test.images},sess)

[[  1.18005773e-05   3.26360328e-10   2.67810919e-05 ...,   9.98005450e-01
    1.98632711e-06   8.88013456e-05]
 [  9.09275468e-03   4.59871853e-06   9.73468542e-01 ...,   2.58960361e-13
    2.75193743e-04   1.99491229e-10]
 [  1.71623458e-06   9.83301401e-01   7.96316098e-03 ...,   2.20750039e-03
    1.65757176e-03   1.27955413e-04]
 ..., 
 [  7.18536075e-09   1.76044619e-08   1.20691425e-06 ...,   3.89562891e-04
    1.29277573e-03   1.74526044e-03]
 [  1.94291442e-05   5.11821454e-05   1.79912786e-05 ...,   9.14351460e-07
    2.69470569e-02   2.11932161e-06]
 [  6.75452156e-06   1.68700102e-12   2.57595038e-05 ...,   4.84162953e-11
    2.43107099e-08   9.94936356e-10]]
